name: Pipeline BotSala57 Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENV_BOT_NOTIFICADOR: PROD # Defina o ambiente aqui (DEV ou PROD)
      ENV_YOUTUBE_CHANNEL_ID: ${{ secrets.ENV_YOUTUBE_CHANNEL_ID }}
      ENV_DISCORD_WEBHOOK_URL: ${{ secrets.ENV_DISCORD_WEBHOOK_URL }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run the application
        run: java -jar target/*.jar # Ajuste o caminho/nome do JAR conforme necessário

      - name: Print environment
        run: echo "Ambiente configurado $ENV_BOT_NOTIFICADOR"
